[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mirelo-sdk"
version = "1.0.4"
description = "Official Mirelo API SDK"
requires-python = ">=3.11"
dependencies = ["httpx>=0.27"]
license = { text = "MIT" }
authors = [{ name = "Mirelo AI GmbH", email = "info@mirelo.ai" }]
readme = "README.md"

[project.urls]
Homepage = "https://mirelo.ai"
Repository = "https://github.com/mirelo-ai/sdk"

[tool.setuptools.packages.find]
where = ["src"]
